/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;



import models.contratos;
import models.Encriptar;
import models.servicio;
import models.BlockChain;
import models.Block;
import java.nio.file.Files;
import java.nio.file.Paths;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;
import org.bouncycastle.openssl.PEMException;
import java.security.spec.X509EncodedKeySpec;
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter;
import org.bouncycastle.openssl.PEMException;// Importante para la conversión
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.util.io.pem.PemObject;
import org.bouncycastle.util.io.pem.PemReader;
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Security;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.SQLException;

/**
 *
 * @author Raul
 */
public class appContratosGUI extends javax.swing.JFrame {

    private final ArrayList<contratos> listaContratos;
    private DefaultComboBoxModel<String> comboModel;
    private BlockChain blockchain;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(appContratosGUI.class.getName());

    /**
     * Creates new form appContratosGUI constructor
     */
    public appContratosGUI() {
        initComponents();
        Security.addProvider(new BouncyCastleProvider());
        this.listaContratos = new ArrayList<>();
        this.blockchain = new BlockChain();
        this.comboModel = new DefaultComboBoxModel<>();
        /*jComboBox1.setModel(comboModel);
        DefaultComboBoxModel<String> estadoModel = new DefaultComboBoxModel<>();
        estadoModel.addElement("Pendiente");
        estadoModel.addElement("En Progreso");
        estadoModel.addElement("Completado");
        jComboBox2.setModel(estadoModel);*/
        actualizarEstadoBlockchain();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonGuardarBC = new javax.swing.JButton();
        jButtonGuardarBC1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jButton3.setText("Reporte html");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reporte json");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cifrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Desencriptar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Minar Bloque");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonGuardarBC.setText("Guardar Cadena de bloques");
        jButtonGuardarBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarBCActionPerformed(evt);
            }
        });

        jButtonGuardarBC1.setText("Validar Cadena");
        jButtonGuardarBC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarBC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGuardarBC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarBC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarBC1)
                .addGap(35, 35, 35))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Bloque"));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Servidor"));

        jLabel14.setText("Servidor");

        jLabel15.setText("Net IP Address");

        jLabel16.setText("Server/Client ports");

        jTextField12.setText("7000");

        jLabel17.setText("and");

        jTextField4.setText("8000");

        jTextField13.setText("127.0.0.1");
        jTextField13.setToolTipText("");

        jTextField14.setToolTipText("");

        jButton11.setText("Crear Servidor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(61, 61, 61)
                        .addComponent(jTextField14))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel17)
                                .addGap(4, 4, 4)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField13)))
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Servidor"));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Server");

        jButton1.setText("Crecar Cliente");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Usuario"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (listaContratos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay contratos para generar el reporte HTML.", "Reporte Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Porción de código para crear el apuntador del archivo con JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte HTML");

        // Configurar el filtro de archivo para HTML
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos HTML (*.html)", "html"));

        int userSelection = fileChooser.showSaveDialog(this);
        File fileToSave = null;

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
            // Asegurarse de que el nombre del archivo termine en .html
            if (!filePath.toLowerCase().endsWith(".html")) {
                fileToSave = new File(filePath + ".html");
            }
        } else {
            return; // El usuario canceló la operación
        }

        // Porción de código para ensamblar el reporte HTML
        StringBuilder htmlContent = new StringBuilder();
        htmlContent.append("<!DOCTYPE html>\n");
        htmlContent.append("<html lang=\"es\">\n");
        htmlContent.append("<head>\n");
        htmlContent.append("    <meta charset=\"UTF-8\">\n");
        htmlContent.append("    <title>Reporte de Contratos</title>\n");
        htmlContent.append("    <style>\n");
        htmlContent.append("        body { font-family: Arial, sans-serif; margin: 20px; background-color: #f4f4f4; color: #333; }\n");
        htmlContent.append("        .container { max-width: 900px; margin: auto; padding: 20px; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }\n");
        htmlContent.append("        h1 { text-align: center; color: #4CAF50; }\n");
        htmlContent.append("        .contrato { border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; border-radius: 5px; background-color: #fafafa; }\n");
        htmlContent.append("        .contrato h2 { color: #2C3E50; margin-top: 0; }\n");
        htmlContent.append("        .servicio { border-left: 3px solid #7f8c8d; padding-left: 10px; margin: 10px 0; }\n");
        htmlContent.append("        .servicio h3 { color: #34495e; }\n");
        htmlContent.append("    </style>\n");
        htmlContent.append("</head>\n");
        htmlContent.append("<body>\n");
        htmlContent.append("    <div class=\"container\">\n");
        htmlContent.append("        <h1>Reporte de Contratos y Servicios</h1>\n");

        for (contratos c : listaContratos) {
            htmlContent.append("        <div class=\"contrato\">\n");
            htmlContent.append("            <h2>Contrato: ").append(c.getIdContrato()).append("</h2>\n");
            htmlContent.append("            <p><strong>Cliente:</strong> ").append(c.getParteA()).append("</p>\n");
            htmlContent.append("            <p><strong>Proveedor:</strong> ").append(c.getParteB()).append("</p>\n");
            htmlContent.append("            <p><strong>Valor Total:</strong> $").append(String.format("%.2f", c.getValorTotal())).append("</p>\n");

            if (!c.getListaServicios().isEmpty()) {
                htmlContent.append("            <h3>Servicios:</h3>\n");
                for (servicio s : c.getListaServicios()) {
                    htmlContent.append("            <div class=\"servicio\">\n");
                    htmlContent.append("                <h4>Servicio: ").append(s.getIdServicio()).append("</h4>\n");
                    htmlContent.append("                <p><strong>Descripción:</strong> ").append(s.getDescripcion()).append("</p>\n");
                    htmlContent.append("                <p><strong>Estado:</strong> ").append(s.getEstado()).append("</p>\n");
                    htmlContent.append("                <p><strong>Monto:</strong> $").append(String.format("%.2f", s.getMontoServicio())).append("</p>\n");
                    htmlContent.append("            </div>\n");
                }
            }
            htmlContent.append("        </div>\n");
        }

        htmlContent.append("    </div>\n");
        htmlContent.append("</body>\n");
        htmlContent.append("</html>\n");

        // Escribir el contenido en un archivo
        try (FileWriter writer = new FileWriter(fileToSave)) {
            writer.write(htmlContent.toString());
            JOptionPane.showMessageDialog(this, "Reporte HTML generado con éxito.", "Reporte Creado", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al escribir el archivo HTML: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
// falta diseno para visualizar los datos
    /**dice anterior
     *  // TODO add your handling code here:
        jTextArea2.setText("");

        // Verificar si la lista de contratos no está vacía
        if (listaContratos.isEmpty()) {
            jTextArea2.append("No hay contratos para listar.");
            return;
        }

        StringBuilder reporte = new StringBuilder();
        reporte.append("=================== REPORTE DE CONTRATOS ===================\n\n");

        for (contratos c : listaContratos) {
            reporte.append("ID Contrato: ").append(c.getIdContrato()).append("\n");
            reporte.append("Cliente: ").append(c.getParteA()).append("\n");
            reporte.append("Proveedor: ").append(c.getParteB()).append("\n");
            reporte.append("Valor Total del Contrato: ").append(String.format("$%.2f", c.getValorTotal())).append("\n");
            reporte.append("--- Servicios del Contrato ---\n");

            if (c.getListaServicios().isEmpty()) {
                reporte.append("   (Este contrato no tiene servicios registrados)\n");
            } else {
                for (servicio s : c.getListaServicios()) {
                    reporte.append("   ID Servicio: ").append(s.getIdServicio()).append("\n");
                    reporte.append("   Descripción: ").append(s.getDescripcion()).append("\n");
                    reporte.append("   Estado: ").append(s.getEstado()).append("\n");
                    reporte.append("   Monto: ").append(String.format("$%.2f", s.getMontoServicio())).append("\n");
                    reporte.append("   ----------------------\n");
                }
            }
            reporte.append("\n");
        }

        // Asignar el reporte completo al JTextArea
        jTextArea2.setText(reporte.toString());
     */
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jTextArea2.setText("");

        // Verificar si la lista de contratos no está vacía
        if (listaContratos.isEmpty()) {
            jTextArea2.append("No hay contratos para listar.");
            return;
        }

        StringBuilder reporte = new StringBuilder();
        reporte.append("=================== REPORTE DE CONTRATOS ===================\n\n");

        for (contratos c : listaContratos) {
            reporte.append("ID Contrato: ").append(c.getIdContrato()).append("\n");
            reporte.append("Cliente: ").append(c.getParteA()).append("\n");
            reporte.append("Proveedor: ").append(c.getParteB()).append("\n");
            reporte.append("Valor Total del Contrato: ").append(String.format("$%.2f", c.getValorTotal())).append("\n");
            reporte.append("--- Servicios del Contrato ---\n");

            if (c.getListaServicios().isEmpty()) {
                reporte.append("   (Este contrato no tiene servicios registrados)\n");
            } else {
                for (servicio s : c.getListaServicios()) {
                    reporte.append("   ID Servicio: ").append(s.getIdServicio()).append("\n");
                    reporte.append("   Descripción: ").append(s.getDescripcion()).append("\n");
                    reporte.append("   Estado: ").append(s.getEstado()).append("\n");
                    reporte.append("   Monto: ").append(String.format("$%.2f", s.getMontoServicio())).append("\n");
                    reporte.append("   ----------------------\n");
                }
            }
            reporte.append("\n");
        }

        // Asignar el reporte completo al JTextArea
        jTextArea2.setText(reporte.toString());
        mostrarUltimoBloqueEnTextArea3();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (listaContratos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay contratos para generar el reporte JSON.", "Reporte Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Porción de código para crear el apuntador del archivo con JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte JSON");

        // Configurar el filtro de archivo para JSON
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos JSON (*.json)", "json"));

        int userSelection = fileChooser.showSaveDialog(this);
        File fileToSave = null;

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
            // Asegurarse de que el nombre del archivo termine en .json
            if (!filePath.toLowerCase().endsWith(".json")) {
                fileToSave = new File(filePath + ".json");
            }
        } else {
            return;
        }

        // Porción de código para ensamblar el reporte JSON
        StringBuilder jsonContent = new StringBuilder();
        jsonContent.append("{\n");
        jsonContent.append("    \"contratos\": [\n");

        for (int i = 0; i < listaContratos.size(); i++) {
            contratos c = listaContratos.get(i);
            jsonContent.append("        {\n");
            jsonContent.append("            \"idContrato\": \"").append(c.getIdContrato()).append("\",\n");
            jsonContent.append("            \"cliente\": \"").append(c.getParteA()).append("\",\n");
            jsonContent.append("            \"proveedor\": \"").append(c.getParteB()).append("\",\n");
            jsonContent.append("            \"valorTotal\": ").append(c.getValorTotal()).append(",\n");
            jsonContent.append("            \"servicios\": [\n");

            if (!c.getListaServicios().isEmpty()) {
                for (int j = 0; j < c.getListaServicios().size(); j++) {
                    servicio s = c.getListaServicios().get(j);
                    jsonContent.append("                {\n");
                    jsonContent.append("                    \"idServicio\": \"").append(s.getIdServicio()).append("\",\n");
                    jsonContent.append("                    \"descripcion\": \"").append(s.getDescripcion()).append("\",\n");
                    jsonContent.append("                    \"estado\": \"").append(s.getEstado()).append("\",\n");
                    jsonContent.append("                    \"monto\": ").append(s.getMontoServicio()).append("\n");
                    jsonContent.append("                }");
                    if (j < c.getListaServicios().size() - 1) {
                        jsonContent.append(",");
                    }
                    jsonContent.append("\n");
                }
            }
            jsonContent.append("            ]\n");
            jsonContent.append("        }");
            if (i < listaContratos.size() - 1) {
                jsonContent.append(",");
            }
            jsonContent.append("\n");
        }
        jsonContent.append("    ]\n");
        jsonContent.append("}\n");

        // Escribir el contenido en un archivo
        try (FileWriter writer = new FileWriter(fileToSave)) {
            writer.write(jsonContent.toString());
            JOptionPane.showMessageDialog(this, "Reporte JSON generado con éxito.", "Reporte Creado", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al escribir el archivo JSON: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Encriptador frmEncriptar = new Encriptador();
        frmEncriptar.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here: 
        Desencriptar desencriptarForm = new Desencriptar();
        desencriptarForm.setVisible(true); // Mostrar la ventana
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (listaContratos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay contratos para incluir en un bloque.", "Sin Datos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Generar JSON (igual que en jButton4ActionPerformed)
    StringBuilder reporte = new StringBuilder();
    reporte.append("{\n");
    reporte.append("  \"contratos\": [\n");
    for (int i = 0; i < listaContratos.size(); i++) {
        contratos c = listaContratos.get(i);
        reporte.append("    {\n");
        reporte.append("      \"idContrato\": \"").append(c.getIdContrato()).append("\",\n");
        reporte.append("      \"cliente\": \"").append(c.getParteA()).append("\",\n");
        reporte.append("      \"proveedor\": \"").append(c.getParteB()).append("\",\n");
        reporte.append("      \"valorTotal\": ").append(c.getValorTotal()).append(",\n");
        reporte.append("      \"servicios\": [\n");
        for (int j = 0; j < c.getListaServicios().size(); j++) {
            servicio s = c.getListaServicios().get(j);
            reporte.append("        {\n");
            reporte.append("          \"idServicio\": \"").append(s.getIdServicio()).append("\",\n");
            reporte.append("          \"descripcion\": \"").append(s.getDescripcion()).append("\",\n");
            reporte.append("          \"estado\": \"").append(s.getEstado()).append("\",\n");
            reporte.append("          \"monto\": ").append(s.getMontoServicio()).append("\n");
            reporte.append("        }");
            if (j < c.getListaServicios().size() - 1) reporte.append(",");
            reporte.append("\n");
        }
        reporte.append("      ]\n");
        reporte.append("    }");
        if (i < listaContratos.size() - 1) reporte.append(",");
        reporte.append("\n");
    }
    reporte.append("  ]\n");
    reporte.append("}\n");

    String jsonContratos = reporte.toString();

    // Minar el bloque
    blockchain.minarBloque(jsonContratos);

    // Actualizar el estado de la cadena
    mostrarUltimoBloqueEnTextArea3();

    JOptionPane.showMessageDialog(this, 
        "Bloque #" + (blockchain.size() - 1) + " minado.\n" +
        "Hash: " + blockchain.obtenerUltimoBloque().getHash(),
        "Blockchain", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonGuardarBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarBCActionPerformed
       try {
        if (blockchain.size() < 1) {
            JOptionPane.showMessageDialog(this, "No hay bloques para guardar.", "Sin Datos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- PASO 1: Seleccionar carpeta de destino ---
        System.out.println("Diálogo de carpeta abierto...");
        JFileChooser dirChooser = new JFileChooser();
        dirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Asegura que solo se seleccionen carpetas
        dirChooser.setDialogTitle("Seleccionar carpeta para guardar la blockchain cifrada");
        if (dirChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            System.out.println("Usuario canceló la selección de carpeta.");
            return; // Usuario canceló
        }

        String carpetaDestino = dirChooser.getSelectedFile().getAbsolutePath();
        System.out.println("Carpeta seleccionada: " + carpetaDestino);

        // Asegurar que la ruta termine con el separador de directorio
        if (!carpetaDestino.endsWith(File.separator)) {
            carpetaDestino += File.separator;
        }
        System.out.println("Carpeta destino final: " + carpetaDestino);

        // Verificar que la ruta sea una carpeta válida
        File carpeta = new File(carpetaDestino);
        if (!carpeta.exists() || !carpeta.isDirectory()) {
            JOptionPane.showMessageDialog(this, "La ruta seleccionada no es una carpeta válida o no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- PASO 2: Seleccionar archivo de clave pública (.pub o .txt) ---
        System.out.println("Diálogo de archivo .pub abierto...");
        JFileChooser pubChooser = new JFileChooser();
        pubChooser.setDialogTitle("Seleccionar archivo de clave pública (.pub o .txt)");
        pubChooser.setFileFilter(new FileNameExtensionFilter("Archivos de Clave Pública (.pub, .txt)", "pub", "txt"));
        pubChooser.setFileSelectionMode(JFileChooser.FILES_ONLY); // Solo archivos

        if (pubChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            System.out.println("Usuario canceló la selección de clave pública.");
            return; // Usuario canceló
        }
        File archivoPub = pubChooser.getSelectedFile();
        System.out.println("Archivo .pub seleccionado: " + archivoPub.getAbsolutePath());

        // Verificar que el archivo exista
        if (!archivoPub.exists()) {
             JOptionPane.showMessageDialog(this, "El archivo de clave pública no existe.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }

        // --- PASO 3: Cargar la clave pública usando Bouncy Castle y PemReader ---
        // Este es el código que funciona, similar al de Desencriptar.java
        PublicKey clavePublica;
        try (FileReader reader = new FileReader(archivoPub);
             org.bouncycastle.openssl.PEMParser parser = new org.bouncycastle.openssl.PEMParser(reader)) { // Usar PEMParser

            Object objeto = parser.readObject();

            if (objeto == null) {
                throw new PEMException("El archivo está vacío o el formato PEM es incorrecto.");
            }

            // Usar JcaPEMKeyConverter
            JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");

            // 1. Manejar SubjectPublicKeyInfo (El formato moderno y más común para claves públicas PEM)
            if (objeto instanceof SubjectPublicKeyInfo) {
                System.out.println("Formato de clave detectado: SubjectPublicKeyInfo");
                clavePublica = converter.getPublicKey((SubjectPublicKeyInfo) objeto);

            // 2. Manejar la conversión de PemObject (si se leyó un objeto genérico)
            // Esto cubre el caso donde PemReader/PemParser devuelve un PemObject simple.
            } else if (objeto instanceof PemObject) {
                PemObject pemObject = (PemObject) objeto;
                if ("PUBLIC KEY".equals(pemObject.getType()) || "RSA PUBLIC KEY".equals(pemObject.getType())) {
                     // Intentar convertir el contenido del PemObject
                     System.out.println("Formato de clave detectado: PemObject (" + pemObject.getType() + ")");
                     SubjectPublicKeyInfo spki = SubjectPublicKeyInfo.getInstance(pemObject.getContent());
                     clavePublica = converter.getPublicKey(spki);
                } else {
                    throw new PEMException("El objeto PEM no es una clave pública válida (Tipo: " + pemObject.getType() + ")");
                }
            }
            
            // 3. Manejar cualquier otro objeto que el conversor pueda manejar directamente
            else if (objeto instanceof PublicKey) {
                System.out.println("Formato de clave detectado: PublicKey directa.");
                clavePublica = (PublicKey) objeto;
            }
            else {
                 throw new PEMException("El archivo no contiene un objeto de clave pública reconocido. Tipo encontrado: " + objeto.getClass().getName());
            }

        } // Fin del try-with-resources (parser y reader se cierran automáticamente)


        System.out.println("Clave pública cargada correctamente.");

        // --- PASO 4: Recorrer cada bloque y guardarlo ---
        int cantidadBloques = blockchain.getCadena().size();
        System.out.println("Cantidad de bloques a guardar: " + cantidadBloques);

        for (Block bloque : blockchain.getCadena()) {
            // Convertir bloque a JSON
            String jsonBloque = "{\n" +
                "  \"indice\": " + bloque.getIndice() + ",\n" +
                "  \"timestamp\": " + bloque.getTimestamp() + ",\n" +
                "  \"hashAnterior\": \"" + bloque.getHashAnterior() + "\",\n" +
                "  \"hash\": \"" + bloque.getHash() + "\",\n" +
                "  \"nonce\": " + bloque.getNonce() + ",\n" +
                "  \"datos\": " + bloque.getDatos() + "\n" +
                "}";

            System.out.println("Convirtiendo bloque " + bloque.getIndice() + " a JSON...");

            // Cifrar el JSON del bloque
            String jsonCifrado = Encriptar.cifrarJSON(jsonBloque, clavePublica);
            System.out.println("Bloque " + bloque.getIndice() + " cifrado.");

            // Crear el nombre del archivo: bloque_0.enc, bloque_1.enc, etc.
            String nombreArchivo = "bloque_" + bloque.getIndice() + ".enc";
            System.out.println("Nombre de archivo para bloque " + bloque.getIndice() + ": " + nombreArchivo);

            // Construir la ruta completa
            String rutaCompleta = carpetaDestino + nombreArchivo;
            System.out.println("Ruta completa para guardar: " + rutaCompleta);

            // --- PASO 5: Escribir el archivo ---
            try (FileWriter writer = new FileWriter(rutaCompleta)) {
                writer.write(jsonCifrado);
                System.out.println("Archivo guardado correctamente: " + rutaCompleta);
            } catch (IOException e) {
                System.err.println("Error al escribir el archivo " + rutaCompleta + ": " + e.getMessage());
                throw e; // Relanza la excepción para que sea capturada por el JOptionPane
            }
        }

        // --- PASO 6: Mensaje de éxito ---
        JOptionPane.showMessageDialog(this,
            "✅ Blockchain guardada como " + cantidadBloques + " archivos cifrados (.enc) en:\n" + carpetaDestino,
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE);
        System.out.println("Proceso de guardado completado exitosamente.");

    } catch (Exception e) {
        e.printStackTrace(); // Muestra el error completo en consola
        JOptionPane.showMessageDialog(this, "Error al guardar la blockchain: " + e.getMessage() + "\n\nMira la consola para más detalles.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonGuardarBCActionPerformed

    private void jButtonGuardarBC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarBC1ActionPerformed
        // TODO add your handling code here:
        if (blockchain.size() <= 1) {
        JOptionPane.showMessageDialog(this, "Necesitas minar bloques para usar la validación de DB.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        System.out.println("\n--- Iniciando validación con PostgreSQL ---");
        
        // Llama al nuevo método de validación
        if (blockchain.esValidaConBaseDeDatos()) {
            JOptionPane.showMessageDialog(this, 
                "VALIDACIÓN EXITOSA: La cadena de bloques es confiable (Hash y Nonce de DB validados).", 
                "Integridad Comprobada", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                "¡FALLO! La cadena ha sido alterada o el Nonce de DB no es el correcto.", 
                "FALLO CRÍTICO", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        // Captura errores de conexión o tabla inexistente.
        JOptionPane.showMessageDialog(this, 
            "ERROR DE CONEXIÓN A DB:Detalles: " + e.getMessage(), 
            "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonGuardarBC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new appContratosGUI().setVisible(true));
    }
    
    private void actualizarEstadoBlockchain() {
        boolean esValida = blockchain.esValida();
        String estado = String.format(
            "Bloques: %d | Estado: %s | Último hash: %s",
            blockchain.size(),
            esValida ? "VÁLIDA" : "INVÁLIDA",
            blockchain.size() > 0 ? blockchain.obtenerUltimoBloque().getHash().substring(0, 12) + "..." : "N/A"
        );
        jTextArea3.setText(estado);
    }
private void mostrarUltimoBloqueEnTextArea3() {
    // 1. Obtener el último bloque de la cadena
    if (blockchain.size() == 0) {
        jTextArea3.setText("La cadena está vacía.");
        return;
    }
    
    Block ultimoBloque = blockchain.obtenerUltimoBloque();

    // 2. Formatear la información del bloque
    // Usaremos los getters de la clase Block
    StringBuilder sb = new StringBuilder();
    sb.append("--- ÚLTIMO BLOQUE DE LA CADENA ---\n");
    sb.append("  Índice: ").append(ultimoBloque.getIndice()).append("\n");
    sb.append("  Timestamp: ").append(ultimoBloque.getTimestamp()).append(" seg\n");
    sb.append("  Nonce: ").append(ultimoBloque.getNonce()).append("\n");
    sb.append("  Hash Anterior: ").append(ultimoBloque.getHashAnterior()).append("\n");
    sb.append("  Hash Actual: ").append(ultimoBloque.getHash()).append("\n");
    sb.append("--------------------------------------\n");
    sb.append("DATOS (Contratos): \n").append(ultimoBloque.getDatos()).append("\n");

    // 3. Establecer el texto en jTextArea3
    jTextArea3.setText(sb.toString());
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonGuardarBC;
    private javax.swing.JButton jButtonGuardarBC1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
